/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registro;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author renzz
 */
public class RegistroA extends javax.swing.JFrame {
    
    DefaultTableModel table =new DefaultTableModel();
    ArrayList<Registro> asistenciaAlumnos =new ArrayList<Registro>();
    

    /**
     * Creates new form RegistroA
     */
    public RegistroA() {
        initComponents();
        this.setTitle("REGISTRO DE ASISTENCIA DE ALUMNOS");
        this.setLocationRelativeTo(null);
        table.addColumn("Nombre");
        table.addColumn("Turno");
        table.addColumn("Curso");
        
        refrescarTabla();
    }
    
    public void refrescarTabla(){
        
        for (Registro nombre : asistenciaAlumnos) {
            Object a[]= new Object [3];
            a[0]= nombre.getNombreA();
            a[1]= nombre.getTurno();
            a[2]= nombre.getCurso();
            
        }
        
        
        
        
        tblRegistroAl.setModel(table);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistroAl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnombreA = new javax.swing.JTextField();
        cboTurnoA = new javax.swing.JComboBox<>();
        cboCursoA = new javax.swing.JComboBox<>();
        btnAgregarA = new javax.swing.JButton();
        btnBorrarA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRegistroAl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRegistroAl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 460, 230));

        jLabel1.setText("Alumno");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setText("Turno");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setText("Curso");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        getContentPane().add(txtnombreA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 90, 20));

        cboTurnoA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mañana", "Tarde", "Noche" }));
        cboTurnoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTurnoAActionPerformed(evt);
            }
        });
        getContentPane().add(cboTurnoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 110, 20));

        cboCursoA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "trigonometria", "geometria", "algebra" }));
        getContentPane().add(cboCursoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 110, 20));

        btnAgregarA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregarA.setText("Agregar");
        btnAgregarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 90, 50));

        btnBorrarA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBorrarA.setText("Borrar");
        btnBorrarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarAActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 100, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboTurnoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTurnoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTurnoAActionPerformed

    private void btnBorrarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarAActionPerformed
        // TODO add your handling code here:
        txtnombreA.setText("");
        cboTurnoA.setSelectedIndex(0);
        cboCursoA.setSelectedIndex(0);
    }//GEN-LAST:event_btnBorrarAActionPerformed

    private void btnAgregarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAActionPerformed
        // TODO add your handling code here:
        Registro nombre = new Registro();
        nombre.setNombreA(txtnombreA.getText());
        nombre.setTurno(cboTurnoA.getSelectedItem().toString());
        nombre.setCurso(cboCursoA.getSelectedItem().toString());
        asistenciaAlumnos.add(nombre);
        refrescarTabla();
        
    }//GEN-LAST:event_btnAgregarAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarA;
    private javax.swing.JButton btnBorrarA;
    private javax.swing.JComboBox<String> cboCursoA;
    private javax.swing.JComboBox<String> cboTurnoA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRegistroAl;
    private javax.swing.JTextField txtnombreA;
    // End of variables declaration//GEN-END:variables
}
